export const DEFAULT_INPUT = `- Back end tech
  - Language
    - Rust
    - Go
  - SQL
    - SQLite
    - MySQL
    - Postgres
- Front end tech
  - Compiler/language
    - Elm
    - Svelte
    - ClojureScript
  - Reactive framework
    - React
    - Vue
    - Angular
  - packager
    - Webpack
    - Snowpack
`
